# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for Maven projects
  - package-ecosystem: "maven"
    directory: "/Forrás Kód/UltimateAntibotRecoded (Kr1S-D)/UltimateAntibot-bungeecord"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/Forrás Kód/UltimateAntibotRecoded (Kr1S-D)/UltimateAntibot-common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/Forrás Kód/UltimateAntibotRecoded (Kr1S-D)/UltimateAntibot-spigot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/Forrás Kód/UltimateAntibotRecoded (Kr1S-D)/UltimateAntibot-velocity"
    schedule:
      interval: "weekly"
