[versions]
paper = "26.1.2.build.65-stable"
canvas = "1.21.11-R0.1-SNAPSHOT"
lombok = "1.18.46"
run-paper = "3.0.2"
shadow = "9.4.1"
placeholderapi = "2.12.2"
vault = "1.7"
folialib = "0.5.2"
worldedit = "7.4.3"
worldguard = "7.0.16"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
canvas = { group = "io.canvasmc.canvas", name = "canvas-api", version.ref = "canvas" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }
folialib = { group = "com.tcoded", name = "FoliaLib", version.ref = "folialib" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }